version: 0.2
env:
  variables:
    MIX_ENV: prod

phases:
  install:
    commands:
      - ASSUME_ROLE_ARN="arn:aws:iam::134209033928:role/CodeBuildAppPipelineRole"
      - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test)
      - env
      - certee-fetch
  build:
    commands:
      - export REGION=eu-west-1
      - export COMPONENTNAME=mozart-fetcher
      - export BUILDPATH=/root/rpmbuiild
      - mix deps.get
      - mix distillery.release
      - mkdir -p ${BUILDPATH}/SOURCES
      - cp _build/prod/rel/mozart_fetcher/releases/*/mozart_fetcher.tar.gz ${BUILDPATH}/SOURCES/
      - tar -zcf ${BUILDPATH}/SOURCES/bake-scripts.tar.gz bake-scripts/
      - cp mozart-fetcher.spec ${BUILDPATH}/SOURCES/
      - cp SOURCES/* ${BUILDPATH}/SOURCES/
      - echo "Generating version file"
      - export COSMOS_VERSION=`cosmos-release generate-version ${COMPONENTNAME}-${REGION}`
      - env
      - rpmbuild --define "_topdir ${BUILDPATH}" --define "version ${COSMOS_VERSION}" -ba mozart-fetcher.spec
  post_build:
    commands:
      # - cosmos-release service "${COMPONENTNAME}-${REGION}" --release-version=v ${BUILDPATH}/RPMS/x86_64/*.x86_64.rpm
      - cosmos-release service "${COMPONENTNAME}-weather-${REGION}" --release-version=v ${BUILDPATH}/RPMS/x86_64/*.x86_64.rpm
      # - cosmos-release service "${COMPONENTNAME}-sport-${REGION}" --release-version=v ${BUILDPATH}/RPMS/x86_64/*.x86_64.rpm