version: 0.2

phases:
  install:
    commands:
      - certee-fetch
  build:
    commands:
      - mix deps.get
      - mix distillery.release
      - mkdir -p /root/rpmbuild/SOURCES
      - cp _build/prod/rel/mozart_fetcher/releases/*/mozart_fetcher.tar.gz /root/rpmbuild/SOURCES/
      - cp mozart-fetcher.spec /root/rpmbuild/SOURCES/
      - cp SOURCES/* /root/rpmbuild/SOURCES/
      - cd /root/rpmbuild/SOURCES
      - echo "Generating version file"
      - export COSMOS_VERSION=`cosmos-release generate-version mozart-fetcher`
      - env
      - rpmbuild --define "_topdir /root/rpmbuild" --define "version ${COSMOS_VERSION}" -ba mozart-fetcher.spec