version: 0.2
env:
  # we need it to access https://github.com/bbc/mozart-fetcher-build
  git-credential-helper: yes
phases:
  install:
    on-failure: ABORT
    commands:
      - certee-fetch
  build:
    on-failure: ABORT
    commands:
      - make dependencies
      - make test
  post_build:
    on-failure: ABORT
    commands:
      - |
        RELEASABLE_BRANCH=$(git branch --contains ${CODEBUILD_RESOLVED_SOURCE_VERSION} --remote | grep -c -E '^\s*origin/master$' || true)
        if [ "${RELEASABLE_BRANCH}" = "1" ] || [ "${FORCE}" = "true" ]; then
          make set_repositories
          make build;
          make release;
        fi
