version: 0.2
env:
  git-credential-helper: yes
  variables:
    COSMOS_CERT: "/etc/pki/tls/certs/client.crt"
    COSMOS_CERT_KEY: "/etc/pki/tls/private/client.key"
phases:
   pre_build:
    on-failure: ABORT
    commands:
      - export RELEASABLE_BRANCH=$(git branch --contains ${CODEBUILD_RESOLVED_SOURCE_VERSION} --remote | grep -c -E '^\s*origin/(main|master)$' || true)
      - export COSMOS_VERSION=$(cosmos-release generate-version mozart-fetcher-eu-west-1)
  install:
    on-failure: ABORT
    commands:
      - certee-fetch
  build:
    on-failure: ABORT
    commands:
      - make dependencies
      - make test
      - make build
  post_build:
    on-failure: ABORT
    commands:
      - |
        set -e
        if [ "${RELEASABLE_BRANCH}" = "1" ] || [ "${FORCE}" = "true" ]; then
          make set_repositories
          make release;
          make deploy;
        else
          echo "No release"
        fi
