version: 0.2
env:
  # we need it to access https://github.com/bbc/mozart-fetcher-build
  git-credential-helper: yes
phases:
  install:
    commands:
      - certee-fetch
  build:
    commands:
      - make dependencies
      - make test
  post_build:
    commands:
      - make set_repositories
      - BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF} | cut -d "/" -f3-)
      - |
        if [ "${BRANCH}"  = "master" ]; then
          make build;
          make release;
        fi
